############################# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: api-gateway-namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: ms1-namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: ms2-namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: ms3-namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: ms4-namespace
---
############################# ResourceQuota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: api-gateway-resource-quota
  namespace: api-gateway-namespace
spec:
  hard:
    limits.cpu: "4"
    limits.memory: 4Gi
    requests.cpu: "2"
    requests.memory: 2Gi
    pods: "2"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ms1-resource-quota
  namespace: ms1-namespace
spec:
  hard:
    limits.cpu: "4"
    limits.memory: 4Gi
    requests.cpu: "2"
    requests.memory: 2Gi
    pods: "2"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ms2-resource-quota
  namespace: ms2-namespace
spec:
  hard:
    limits.cpu: "4"
    limits.memory: 4Gi
    requests.cpu: "2"
    requests.memory: 2Gi
    pods: "2"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ms3-resource-quota
  namespace: ms3-namespace
spec:
  hard:
    limits.cpu: "4"
    limits.memory: 4Gi
    requests.cpu: "2"
    requests.memory: 2Gi
    pods: "2"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ms4-resource-quota
  namespace: ms4-namespace
spec:
  hard:
    limits.cpu: "4"
    limits.memory: 4Gi
    requests.cpu: "2"
    requests.memory: 2Gi
    pods: "2"
---
############################# LimitRange
apiVersion: v1
kind: LimitRange
metadata:
  name: api-gateway-limit-range
  namespace: api-gateway-namespace
spec:
  limits:
  - max:
      cpu: "4"
      memory: "4Gi"
    min:
      cpu: "1"
      memory: "1Gi"
    default:
      cpu: "2"
      memory: "2Gi"
    defaultRequest:
      cpu: "1"
      memory: "1Gi"
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: ms1-limit-range
  namespace: ms1-namespace
spec:
  limits:
  - max:
      cpu: "4"
      memory: "4Gi"
    min:
      cpu: "1"
      memory: "1Gi"
    default:
      cpu: "2"
      memory: "2Gi"
    defaultRequest:
      cpu: "1"
      memory: "1Gi"
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: ms2-limit-range
  namespace: ms2-namespace
spec:
  limits:
  - max:
      cpu: "4"
      memory: "4Gi"
    min:
      cpu: "1"
      memory: "1Gi"
    default:
      cpu: "2"
      memory: "2Gi"
    defaultRequest:
      cpu: "1"
      memory: "1Gi"
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: ms3-limit-range
  namespace: ms3-namespace
spec:
  limits:
  - max:
      cpu: "4"
      memory: "4Gi"
    min:
      cpu: "1"
      memory: "1Gi"
    default:
      cpu: "2"
      memory: "2Gi"
    defaultRequest:
      cpu: "1"
      memory: "1Gi"
    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: ms4-limit-range
  namespace: ms4-namespace
spec:
  limits:
  - max:
      cpu: "4"
      memory: "4Gi"
    min:
      cpu: "1"
      memory: "1Gi"
    default:
      cpu: "2"
      memory: "2Gi"
    defaultRequest:
      cpu: "1"
      memory: "1Gi"
    type: Container