apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms4-deployment
  namespace: ms4-namespace
  annotations:
    kubernetes.io/change-cause: "Initial Deploy"
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: ms4-pod
  template:
    metadata:
      labels:
        app: ms4-pod
    spec:
      containers:
        - name: ms4-container
          image: gmahechas/ms4-nestjs
          imagePullPolicy: IfNotPresent
          env:
            - name: MS4_PORT
              valueFrom:
                secretKeyRef:
                  name: ms4-secret
                  key: MS4_PORT
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: ms4-secret
                  key: MONGODB_URI
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: ms4-secret
                  key: MONGODB_USER
            - name: MONGODB_PASS
              valueFrom:
                secretKeyRef:
                  name: ms4-secret
                  key: MONGODB_PASS
          ports:  
            - containerPort: 50004
---
apiVersion: v1
kind: Service
metadata:
  name: ms4-service
  namespace: ms4-namespace
spec:
  type: ClusterIP
  selector:
    app: ms4-pod
  ports:
    - protocol: TCP
      port: 50004
      targetPort: 50004