name: deplay-mf-0

on:
  push:
    branches:
      - main
    paths:
      - 'packages/0/mf-0-reactjs/**'

defaults:
  run:
    working-directory: packages/0/mf-0-reactjs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Configure AWS credentials from Production account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CLI_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CLI_SECRET_KEY_ID }}
          aws-region: us-east-2

      - name: Copy files to the production website with the AWS CLI
        run: |
          aws s3 sync dist s3://${{ secrets.AWS_S3_ERP_BUCKET_NAME }}/mf-0-reactjs/latest